### ISSUE TITLE
Issue creating a service on Monolith

### ISSUE THREAD

**Issue by undjike** [lucidarch/lucid#1]
After installing `composer require lucidarch/lucid` and initializing `lucid init:monolith`, creating a service `lucid make:service Web` display an error.

> App namespace not set in composer.json
> ....\vendor\lucidarch\lucid\src\Finder.php at 143

But seems like the service is generated though.

![image](https://user-images.githubusercontent.com/57102409/101243790-cf298880-3702-11eb-91ca-a5b0bb1090d1.png)

**Comment by undjike** [comment]
I can notice that the service provider is not generated.

**Comment by undjike** [comment]
Wow, I try to remove the wrongly generated service `lucid delete:service Web`. And it displays...

> This functionality is disabled in a Microservice

As if, it's a micro initialization (but it's not, as I initialized with `lucid init:monolith`.

**Comment by undjike** [comment]
I solved these issues by

- Sanitizing _pseudo-directory_ path comparison 

![image](https://user-images.githubusercontent.com/57102409/101266950-fb212a00-3753-11eb-801c-b57bbb20c2e4.png)

Because the problem was about string comparison `'app/' === 'app\'`

- Correcting one or 2 other things

![image](https://user-images.githubusercontent.com/57102409/101267162-2c025e80-3756-11eb-9eab-5b3a38fc56da.png)


The difficult part is now the logic to know whether the initialization was Micro or Monolith.
That's the reason of the issue with the `lucid delete:service` command (which checks Micro or Monolith initialization).

My workaround is the following...
![image](https://user-images.githubusercontent.com/57102409/101267435-e98e5100-3758-11eb-8f33-f5387bd508e2.png)

But surely, it will break if a `Services` directory is created manually.

**Comment by undjike** [comment]
@Mulkave why not make use of config for that ? 🤔 I mean, publishing config so that we can set the initialization type. So, typing just `lucid init` will initialize regarding the configurations.

**Comment by Mulkave** [comment]
@undjike thanks for digging this up! Sorry to hear you faced this issue. Will fix later today.

> why not make use of config for that ? 🤔 I mean, publishing config so that we can set the initialization type. So, typing just lucid init will initialize regarding the configurations.

because that way it would require two steps to initialise. At some point there will be a `config/lucid.php` file to configure things such as the bas class you'd like to use for features, jobs and operations. Will consider this suggestion as soon as that file is introduced 👍

**Comment by Mulkave** [comment]
@undjike this was tremendously helpful, thanks for digging it up!

- [x] Sanitizing pseudo-directory path comparison
- [x] Correct source directory name (now we're only using `app` so no need to figure it out otherwise
- [x] Indeed it is the correct way to know whether it's a Micro or a Monolith is to check for the `Services` directory for it is the only thing that makes all the difference

Fix now available in [v1.0.2](https://github.com/lucidarch/lucid/releases/tag/v1.0.2), please update the package to get the fixes 😉 

> I can notice that the service provider is not generated.

this was probably due to the failure that occurred before getting to the point of generating it. Tested and provider is being generated as expected.

**Comment by undjike** [comment]
🙏

**Comment by undjike** [comment]
Thanks @Mulkave. You're the best.
