### ISSUE TITLE
use request validate, got 301

### ISSUE THREAD

**Issue by nilsir** [lucidarch/lucid#13]
when i use request validate in feature, got 301 to many times, would you help me?
![image](https://user-images.githubusercontent.com/15967737/102610725-9f4d9c80-4168-11eb-99d6-0139a552cfc6.png)
![image](https://user-images.githubusercontent.com/15967737/102610741-a8d70480-4168-11eb-935d-16b20a51f354.png)

**Comment by Mulkave** [comment]
@nilsir can you please add your Route and Controller code that's serving this feature?

**Comment by nilsir** [comment]
> @nilsir can you please add your Route and Controller code that's serving this feature?

yes, i set it
![image](https://user-images.githubusercontent.com/15967737/102612226-521efa00-416b-11eb-997c-8903f67b5840.png)
![image](https://user-images.githubusercontent.com/15967737/102612273-6236d980-416b-11eb-9e2a-26d6a05ea88c.png)

**Comment by Mulkave** [comment]
I've recreated your example locally and was only able to get the redirect response when i don't pass the `name` in the URL, which is what's expected according to your `UserRequest`.

Visiting `http://localhost:8000/users?name=123` (using `php artisan serve`) works. However, if you visit `https://localhost:8000/users` it will redirect home because it is invalid. This is Laravel's default FormRequest validation behaviour. If you wish to change that you may need to look at [after hook](https://laravel.com/docs/8.x/validation#adding-after-hooks-to-form-requests) and there's also an example of using it in the Lucid docs here: https://docs.lucidarch.dev/validation/#requests-as-unit-dispatchers

**Comment by nilsir** [comment]
> I've recreated your example locally and was only able to get the redirect response when i don't pass the `name` in the URL, which is what's expected according to your `UserRequest`.
> 
> Visiting `http://localhost:8000/users?name=123` (using `php artisan serve`) works. However, if you visit `https://localhost:8000/users` it will redirect home because it is invalid. This is Laravel's default FormRequest validation behaviour. If you wish to change that you may need to look at [after hook](https://laravel.com/docs/8.x/validation#adding-after-hooks-to-form-requests) and there's also an example of using it in the Lucid docs here: https://docs.lucidarch.dev/validation/#requests-as-unit-dispatchers

thank you bro, "lucidarch/lucid" is awesome, i'll try again

**Comment by Mulkave** [comment]
@nilsir were you able to resolve this?

**Comment by nilsir** [comment]
> @nilsir were you able to resolve this?

yes，it’s work ok now, thank you.
